group_keys=False for compatibility with pandas>=1.5
Otherwise, we get
ValueError: 'vjlen_id' is both an index level and a column label, which is ambiguous.